FROM python:3.10
WORKDIR /dashboard
COPY requirements.txt . 
RUN pip3 install -r requirements.txt

COPY dashboard.py .
COPY db_queries.py .

EXPOSE 8501
CMD ["streamlit", "run", "dashboard.py", , "--server.port=8501"]